| 参数符号 | 参数说明 |
|---|---|
| \( n \)    | 装载货物总数量    |
| \( m_{jm} \)    | \( j \) 型集装箱的最大载质量    |
| \( l_p, w_p, h_p, m_p, v_i \) | 第 \( i \) 个货物的长、宽、高、质量和体积 |
| \( L_p, W_p, H_p, V_p, m_i \) | \( j \) 型集装箱的长、宽、高、容量和质量 |
| \((g_i', g_j', g_i')\) | 第 \( i \) 个货物重心坐标    |
| \((con_x, con_y)\) | 集装箱重心位置 \( x \) 坐标安全范围    |
| \((con_y, con_z) \setminus (0, con_z)\) | 集装箱重心位置 \( y, z \) 坐标安全范围    |
| \( I_k, w_k, h_k \) | 第 \( k \) 个货物的长、宽和高    |
| \((x_i, y_i, z_i) \setminus (x_j', y_j', z_j')\) | 第 \( i \) 个货物位置的左后下坐标和右前上坐标 |